자료형
ohahaha29/codeit_JS pull request #2
Opened 2021-03-01 12:22 UTC by ohahaha29

2021-03-01 12:29 UTC, paulk-async requested changes
연산 -> 출력 -> 연산 -> 출력 으로 코드를 수정해주세요.

2021-03-01 12:29 UTC, paulk-async commented on in_javascript/index.js
> +result1 = material1 + String(material5);
이 코드 때문에 윗줄의 결과가 바뀜.
그리고 이 계산은 number와 string의 연산이라 불가함.

2021-03-02 03:03 UTC, ohahaha29 commented on in_javascript/index.js
> +result1 = material1 + String(material5);
JS 의 경우 우선순위에 따라 숫자가 문자열로 치환됨.

2021-03-02 03:22 UTC, paulk-async approved these changes

2021-03-02 03:23 UTC, paulk-async approved these changes

2021-03-02 03:46 UTC, merged